### ISSUE TITLE
"Unhandled promise rejection" error in console with npm start

### ISSUE THREAD

**Issue by alvarofvr** [aviabird/angularspree#91]
Hi guys! 
I'm new to angularjs and to learn it I decided to use your application.
When i start it with `npm start` the browser console give me this error:

```
Unhandled Promise rejection: StaticInjectorError(AppModule)[UserEffects -> Actions]: 
  StaticInjectorError(Platform: core)[UserEffects -> Actions]: 
    NullInjectorError: No provider for Actions! ; Zone: <root> ; Task: Promise.then ; Value: Error: StaticInjectorError(AppModule)[UserEffects -> Actions]: 
  StaticInjectorError(Platform: core)[UserEffects -> Actions]: 
    NullInjectorError: No provider for Actions!
    at _NullInjector.get (webpack-internal:///./node_modules/@angular/core/esm5/core.js:1218)
    at resolveToken (webpack-internal:///./node_modules/@angular/core/esm5/core.js:1516)
    at tryResolveToken (webpack-internal:///./node_modules/@angular/core/esm5/core.js:1458)
    at StaticInjector.get (webpack-internal:///./node_modules/@angular/core/esm5/core.js:1326)
    at resolveToken (webpack-internal:///./node_modules/@angular/core/esm5/core.js:1516)
    at tryResolveToken (webpack-internal:///./node_modules/@angular/core/esm5/core.js:1458)
    at StaticInjector.get (webpack-internal:///./node_modules/@angular/core/esm5/core.js:1326)
    at resolveNgModuleDep (webpack-internal:///./node_modules/@angular/core/esm5/core.js:11070)
    at _createClass (webpack-internal:///./node_modules/@angular/core/esm5/core.js:11111)
    at _createProviderInstance$1 (webpack-internal:///./node_modules/@angular/core/esm5/core.js:11081) Error: StaticInjectorError(AppModule)[UserEffects -> Actions]: 
  StaticInjectorError(Platform: core)[UserEffects -> Actions]: 
    NullInjectorError: No provider for Actions!
    at _NullInjector.get (webpack-internal:///./node_modules/@angular/core/esm5/core.js:1218:19)
    at resolveToken (webpack-internal:///./node_modules/@angular/core/esm5/core.js:1516:24)
    at tryResolveToken (webpack-internal:///./node_modules/@angular/core/esm5/core.js:1458:16)
    at StaticInjector.get (webpack-internal:///./node_modules/@angular/core/esm5/core.js:1326:20)
    at resolveToken (webpack-internal:///./node_modules/@angular/core/esm5/core.js:1516:24)
    at tryResolveToken (webpack-internal:///./node_modules/@angular/core/esm5/core.js:1458:16)
    at StaticInjector.get (webpack-internal:///./node_modules/@angular/core/esm5/core.js:1326:20)
    at resolveNgModuleDep (webpack-internal:///./node_modules/@angular/core/esm5/core.js:11070:25)
    at _createClass (webpack-internal:///./node_modules/@angular/core/esm5/core.js:11111:29)
    at _createProviderInstance$1 (webpack-internal:///./node_modules/@angular/core/esm5/core.js:11081:26)
```
How can i fix this?

My configurations: 
```
Angular CLI: 1.7.4
Node: 8.9.4
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.4.2
webpack: 3.11.0
```

**Comment by pkrawat1** [comment]
please reopen this if issue is coming on latest master.
